language: csharp
solution: Main.sln
mono: none
dotnet: 2.1.200

install:
- dotnet restore
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- nuget restore Main.sln

script:
- dotnet build