language: csharp
solution: Main.sln

install:
- nuget restore Main.sln
- nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Main.sln
  - ls ./testrunner/NUnit.ConsoleRunner.3.8.0/tools